version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: app_graph_db
    environment:
      NEO4J_AUTH: "neo4j/Admin1234!"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - app_neo4j_data:/data

  api:
    build: .
    container_name: app_graph_api
    depends_on:
      - neo4j
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=1
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=Admin1234!
    command: flask run
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  app_neo4j_data:
    external: true
    name: app_neo4j_data